version: '3.9'

services:
  web:
    image: ghcr.io/timothee-durand/portfolio-2022:main
    hostname: timotheedurand.fr
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.web.rule=Host(`timotheedurand.fr`)
        - traefik.http.services.web.loadbalancer.server.port=80
    restart: always
    networks:
      - vps

networks:
  vps:
    name: vps
    driver: overlay
    attachable: true
    external: true

